server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/fitness_user_db
    username: postgres
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

